### ISSUE TITLE
Different filters depending on site

### ISSUE THREAD

**Issue by FelixSFD** [SOBotics/Natty#23]
If we add support for more pages in the SE-network, we should make lists that define, which filters are used on which site. This could be achieved by adding the interface `FilterList` and classes like `StackOverflowFilterList` and `AskUbuntuFilterList` that are implementing this interface

**Comment by Bhargav-Rao** [comment]
Yes, this is quite simple to implement. Just like the command lists, we need to pass another object, for that. I'll try to find some time and implement it.

**Comment by Bhargav-Rao** [comment]
I found a simpler way of doing this by passing the `sitename` as a parameter while doing the filters check, I refactored it in commit 65638f982c39f2783ee66f38f17d4cf78d5978a0. 

Unlike the command lists, which was per room, the filters list is per site, hence my previous comment about passing an additional object, is not that suitable. 

I am still to decide whether to have an interface `FiltersList`, or just leave it in the way I've done it now.
