### ISSUE TITLE
Can't insert multiple spaces fetween feedbacks in `@natty send`

### ISSUE THREAD

**Issue by abenkovskii** [SOBotics/Natty#3]
`send f t u t u u t t          t t t f t t t t         t f ` yields "Too many feedbacks, Too less reports".
https://chat.stackoverflow.com/transcript/message/34836989#34836989
I think it's because you are simply splitting the string on every space or counting spaces somewhere.

**Comment by Bhargav-Rao** [comment]
This is fixed by using `getPlainContent` from the Chatlib rather than using `getContent`. StackExchange trims the spaces, so using `getPlainContent` returns a string with the double spaces stripped.
