### ISSUE TITLE
Manually reporting NAAs provides only FMS link

### ISSUE THREAD

**Issue by Filnor** [SOBotics/Natty#36]
When you report an answer manually using the report command, [Natty only provides a FMS link](https://chat.stackoverflow.com/transcript/message/42909128#42909128), instead of Sentinel, even if Sentinel is up.

For consintency, this should be handled the same way as in normal reporting, where FMS is only used when Sentinel is not reachable/down.

**Comment by Bhargav-Rao** [comment]
Manual reports also return a Sentinel link. All these were manual reports https://sentinel.erwaysoftware.com/search?utf8=%E2%9C%93&q=&feedback=3&commit=Search&min_score=
